try
    purge
end


[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
cDirSrc = fullfile(cDirThis, '..', '..', 'src');
cDirMpm = fullfile(cDirThis, '..', '..', 'mpm-packages');

% Dependencies
addpath(genpath(cDirSrc));
addpath(genpath(cDirMpm));

% Optionally configure with the directory where waveforms are saved
% The default is to use pwd

cDir = fullfile( ...
    cDirThis, ...
    'save' ...
);

dScreenSize = get(0, 'ScreenSize');
        
dWidth = 850;
dHeight = 180;

hFigure = figure( ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'Name', 'LC400 Test', ...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
     ]... % left bottom width height
);

clock = mic.Clock('master'); 
uiClock = mic.ui.Clock(clock);
np = npoint.LC400Virtual();

app = npoint.ui.LC400(...
    'fhGetNPoint', @() np, ...
    'clock', clock, ...
    'uiClock', clock, ...
    'fhGet20BitWaveforms', @get20BitWaveforms, ...
    'cName', 'Test' ...
);
app.build(hFigure, 10, 10);